name: AWS Terraform Workflow For Batch DevSecOps B49
on:
  pull_request:
    types:
    - closed
    branches:
      - development
      - production
    paths-ignore:
      - 'Manual.yml'
      - 'ReadMe.md'
  push:
    branches:
      - development
      - production
    paths-ignore:
      - 'Manual.yml'
      - 'ReadMe.md'

#Use PR rather than push as most of the clients using PR for merging branches.

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "us-east-1"
  ENV_DESTROY: "NO"
  TERRAFORM_DESTROY: ${{ vars.TERRAFORM_DESTROY}}
  TERRAFORM_VERSION: "1.14.0"

jobs:
  terraform-checkov:
    if: ${{ vars.TERRAFORM_DESTROY == 'NO' }}
    name: 'Stage_1 - Checkov Security Scan For Terraform Code'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print Runner Hostname
        run: echo $HOSTNAME
      - name: Setup Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./development
          quiet: true
          soft_fail: true # If Given False, Action Fails when Checkov finds issues. 
          output_format: cli,json
          output_file_path: console,./development/results.json
      - name: Upload file to bucket
        uses: koraykoska/s3-upload-github-action@master
        env:
          FILE: ./development/results.json
          S3_ENDPOINT: 's3.us-east-1.amazonaws.com'
          S3_BUCKET: "terraformbkp0212"
          S3_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}